name: "♻️ Refactoring"
description: "코드 리팩토링이 필요한 경우 작성하는 이슈 템플릿입니다."
labels: ["refactor"]
body:
  - type: textarea
    attributes:
      label: 📄 리팩토링 개요
      description: 리팩토링이 필요한 이유와 개선할 부분을 설명해주세요.
      placeholder: "예: 코드 중복 제거, 성능 최적화 필요"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 🚀 리팩토링 목표
      description: 리팩토링을 통해 기대하는 효과를 선택해주세요.
      options:
        - label: "코드 가독성 향상"
        - label: "성능 개선"
        - label: "테스트 코드 추가"
        - label: "비즈니스 로직 분리"
  - type: textarea
    attributes:
      label: 📌 개선 방향
      description: 어떤 방식으로 리팩토링할 계획인지 설명해주세요.
      placeholder: |
        - 특정 클래스를 분리하여 책임 분리
        - 반복되는 로직을 유틸 함수로 변경
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📝 참고 자료
      description: 관련 문서, 링크 등이 있다면 추가해주세요.
      placeholder: "예: 디자인 패턴 문서, 기존 코드 링크 등"